"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, KeyRound, ShieldCheck } from "lucide-react";
import { DataPageShell } from "../../components/data-page";
import { Button } from "../../components/ui/button";
import { api, type AuthUser } from "../../lib/api";
import Image from "next/image";

export default function SettingsPage() {
  const [user, setUser] = useState<AuthUser | null>(null); const [enabled, setEnabled] = useState(false); const [setup, setSetup] = useState<{ qrCodeDataUri: string; secret: string } | null>(null); const [code, setCode] = useState(""); const [password, setPassword] = useState(""); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { api.me().then((r) => { setUser(r.user); setEnabled(r.user.mfaEnabled); setLoading(false); }).catch((e) => { setError(e instanceof Error ? e.message : "Não foi possível carregar as configurações."); setLoading(false); }); }, []);
  async function begin() { setSaving(true); setError(""); try { const r = await api.mfaSetup(); setSetup(r); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível iniciar o MFA."); } finally { setSaving(false); } }
  async function confirm() { setSaving(true); setError(""); try { await api.mfaConfirm(code); setEnabled(true); setSetup(null); setCode(""); setSuccess("MFA ativado com sucesso."); } catch (e) { setError(e instanceof Error ? e.message : "Código inválido."); } finally { setSaving(false); } }
  async function disable() { setSaving(true); setError(""); try { await api.mfaDisable(password, code); setEnabled(false); setPassword(""); setCode(""); setSuccess("MFA desativado."); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível desativar o MFA."); } finally { setSaving(false); } }
  async function changePassword() { setSaving(true); setError(""); try { await api.changePassword(currentPassword, newPassword); setCurrentPassword(""); setNewPassword(""); setSuccess("Senha alterada com sucesso."); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível alterar a senha."); } finally { setSaving(false); } }
  return <DataPageShell active="/settings"><div className="page-heading"><div><span className="eyebrow">Preferências</span><h1>Configurações</h1><p>Proteja sua conta e consulte as opções disponíveis.</p></div></div>{loading ? <div className="panel panel-empty">Carregando configurações...</div> : <>{error && <div className="callout error-callout">{error}</div>}{success && <div className="callout success-callout">{success}</div>}<div className="panel"><div className="panel-heading"><div><h2>Autenticação multifator</h2><p>Adicione uma camada extra de segurança usando um autenticador TOTP.</p></div><ShieldCheck className="panel-icon" /></div><div style={{ marginTop: 24 }}>{enabled ? <div className="settings-status"><CheckCircle2 size={20} /><span>MFA está ativo nesta conta.</span><Button variant="secondary" onClick={() => setEnabled(false)}>Gerenciar desativação</Button></div> : setup ? <div className="mfa-setup"><Image unoptimized src={setup.qrCodeDataUri} alt="QR Code para configurar MFA" width={180} height={180} /><p>Escaneie o QR Code ou use a chave <code>{setup.secret}</code> no seu autenticador.</p><input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} placeholder="Código de 6 dígitos" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} /><Button disabled={saving || code.length !== 6} onClick={confirm}>Confirmar MFA</Button></div> : <Button disabled={saving} onClick={begin}><KeyRound size={16} /> Configurar MFA</Button>}{enabled && <div className="mfa-disable"><input type="password" placeholder="Senha atual" value={password} onChange={(e) => setPassword(e.target.value)} /><input inputMode="numeric" maxLength={6} placeholder="Código TOTP" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} /><Button variant="secondary" disabled={saving || !password || code.length !== 6} onClick={disable}>Desativar MFA</Button></div>}</div></div><div className="panel" style={{ marginTop: 14 }}><h2>Perfil</h2><p className="panel-description">{user?.name} · {user?.email}</p><div className="form-grid" style={{ marginTop: 18 }}><label>Senha atual<input type="password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /></label><label>Nova senha<input type="password" minLength={8} value={newPassword} onChange={(e) => setNewPassword(e.target.value)} /></label><div className="dialog-actions"><Button disabled={saving || !currentPassword || newPassword.length < 8} onClick={() => void changePassword()}>Alterar senha</Button></div></div></div></>}</DataPageShell>;
}
