// Ações de auditoria. Nunca registrar secrets, tokens ou senhas (AGENTS.md §17).
export const AuditAction = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  TENANT_CREATED: 'TENANT_CREATED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  // Fases futuras:
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_DELETED: 'CUSTOMER_DELETED',
  CARRIER_CREATED: 'CARRIER_CREATED',
  CARRIER_UPDATED: 'CARRIER_UPDATED',
  CARRIER_DELETED: 'CARRIER_DELETED',
  SIMULATION_CREATED: 'SIMULATION_CREATED',
  IMPORT_STARTED: 'IMPORT_STARTED',
  IMPORT_COMPLETED: 'IMPORT_COMPLETED',
  IMPORT_FAILED: 'IMPORT_FAILED',
  SEED_COMPLETED: 'SEED_COMPLETED',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];
