"use client";
import { useCallback, useEffect, useState } from "react";
import { ClipboardList, Filter } from "lucide-react";
import { DataPageShell } from "../../components/data-page";
import { SortableTable } from "../../components/sortable-table";
import { api, type AuditLog, type AuthUser } from "../../lib/api";

export default function AuditPage() {
  const [session, setSession] = useState<AuthUser | null>(null); const [logs, setLogs] = useState<AuditLog[]>([]); const [action, setAction] = useState(""); const [entity, setEntity] = useState(""); const [page, setPage] = useState(1); const [meta, setMeta] = useState({ total: 0, totalPages: 1 }); const [loading, setLoading] = useState(true); const [sessionLoading, setSessionLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const r = await api.audit(`${action ? `&action=${encodeURIComponent(action)}` : ""}${entity ? `&entity=${encodeURIComponent(entity)}` : ""}&page=${page}`); setLogs(r.data); setMeta(r.meta); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível carregar a auditoria."); } finally { setLoading(false); } }, [action, entity, page]);
  useEffect(() => { api.me().then((r) => setSession(r.user)).catch((e) => setError(e instanceof Error ? e.message : "Sua sessão não está disponível.")).finally(() => setSessionLoading(false)); }, []);
  useEffect(() => { if (!session) return; const timer = window.setTimeout(() => { if (session.role !== "OPERATOR") void load(); else setLoading(false); }, 0); return () => window.clearTimeout(timer); }, [session, load]);
  return <DataPageShell active="/audit"><div className="page-heading"><div><span className="eyebrow">Rastreabilidade</span><h1>Auditoria</h1><p>Acompanhe ações relevantes realizadas no tenant.</p></div></div>{sessionLoading ? <div className="panel panel-empty">Verificando sua sessão...</div> : session?.role === "OPERATOR" ? <div className="panel panel-empty"><ClipboardList size={25} /><strong>Acesso restrito</strong><span>A auditoria está disponível para administradores e gestores.</span></div> : <><div className="data-toolbar"><div className="search-field"><Filter size={16} /><select value={action} onChange={(e) => { setPage(1); setAction(e.target.value); }}><option value="">Todas as ações</option>{["LOGIN", "LOGOUT", "USER_CREATED", "USER_UPDATED", "USER_DELETED", "ROLE_CHANGED", "MFA_ENABLED", "MFA_DISABLED", "SIMULATION_CREATED", "IMPORT_COMPLETED", "IMPORT_FAILED"].map((v) => <option key={v}>{v}</option>)}</select><select value={entity} onChange={(e) => { setPage(1); setEntity(e.target.value); }}><option value="">Todas as entidades</option>{["User", "Customer", "Carrier", "Simulation", "Import"].map((v) => <option key={v}>{v}</option>)}</select></div><span className="toolbar-count">{meta.total} registros</span></div>{error && <div className="callout error-callout">{error}</div>}<div className="data-panel"><SortableTable><thead><tr><th>Ação</th><th>Usuário</th><th>Entidade</th><th>Data</th></tr></thead><tbody>{loading ? <tr><td colSpan={4}><div className="table-skeleton" /></td></tr> : logs.map((log) => <tr key={log.id}><td><strong>{log.action}</strong></td><td>{log.user?.name ?? "Sistema"}<small>{log.user?.email}</small></td><td>{log.entity}{log.entityId ? ` · ${log.entityId.slice(0, 8)}` : ""}</td><td>{new Date(log.createdAt).toLocaleString("pt-BR")}</td></tr>)}{!loading && !logs.length && <tr><td colSpan={4}><div className="empty-table"><ClipboardList size={24} /><strong>Nenhum evento encontrado</strong><span>Tente remover o filtro selecionado.</span></div></td></tr>}</tbody></SortableTable></div><div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Anterior</button><span>Página {page} de {meta.totalPages}</span><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}>Próxima</button></div></>}</DataPageShell>;
}
